### ISSUE TITLE
update fruit affinity css

### ISSUE THREAD

**Issue by dudethatbe** [datafruits/datafruits#1036]
seems like people are actually looking at this graph so now'd be a good time to start styling it to fit the site

**Comment by mcfiredrill** [comment]
:100: 

I picked this library because it was the fastest thing to get going, but not super happy with it.
https://www.chartjs.org/docs/latest/charts/radar.html

Ultimately I'd like to handroll our own chart but maybe we can at least try to customize the chart.js radar chart to match the rest of the site's colors.

**Comment by dudethatbe** [comment]
who would have thought there would have been 0 CSS involved with this? I'm changing my approach from loading the same color config that Tailwind uses, to simply copy-pasting those values into Chart.js. @mcfiredrill  you still down to make your own radar graph ? 😎

**Comment by mcfiredrill** [comment]
> @mcfiredrill you still down to make your own radar graph ? sunglasses

Someday, but if we can figure out a solution in the short term that would be great I think. :))))))))
