### ISSUE TITLE
calendar doesn't show any shows sometimes

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#232]

**Comment by dudethatbe** [comment]
A common case is when someone has the calendar page open before the event was created/modified. Refreshing the page has always fixed it for me. Maybe a refresh button included with the calendar component would help? It's not that big of a deal to refresh the entire page, but it would be nice, to only have to load a page of shows instead of the entire page. This is mostly for people like me who _know_ that a show should be showing up somewhere yet _insist_ on keeping numerous tabs of datafruits open.

**Comment by mcfiredrill** [comment]
We changed the calendar completely.
