### ISSUE TITLE
hamburger menu doesn't appear in screen some sizes in safari

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#557]
reported by ralin on the discord
https://discord.com/channels/192542105741033472/494643980760252440/786322603932385351
![dataftest](https://user-images.githubusercontent.com/66243/101704825-ebde0b80-3ac8-11eb-9e7f-8a450cfa6c30.gif)

Safari version 14.0, MacOs version 10.15.7

**Comment by HawkinsJM** [comment]
Hi. This is Ralin from the Discord. I don't have anything else to add, but let me know if there is any more information I can give you or something I can test.

**Comment by jcherven** [comment]
i've been secretly poking every now and then at this for over a year (unsuccessfully), feels like the cause is some deep, opaque safari css implementation quirk. BUT as of now the menu appears to be working correctly in safari 14.0.3 (latest in catalina) and ios safari on my iphone 7. i'm guessing either apple recently added the flex property support for this to safari, or one of the recent dependabot version bumps of the css processor fixed it??? weird. can others check on their abblefruit devices and confirm?
![Screen Shot 2021-02-24 at 3 30 53 PM](https://user-images.githubusercontent.com/1672289/109062036-67f1f380-76b5-11eb-94dd-dbdc1dab21d9.png)

**Comment by HawkinsJM** [comment]
It is working correctly for me now too. Also Safari 14.0.3 on Catalina. Thanks for looking into it.
